server:
  port: 8081

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8092/realms/my-realm}
          #container --> issuer-uri: http://keycloack:8080/realms/my-realm
          #locally --> issuer-uri: http://localhost:8092/realms/my-realm
  kafka:
    bootstrap-servers: localhost:9092
    bookingTopic: booking
    consumer:
      group-id: booking-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.algerage.search.domain.model.BookingMessage"
