server:
  port: 8081

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8091/realms/my-realm}
          #container --> issuer-uri: http://keycloack:8080/realms/my-realm
          #locally --> issuer-uri: http://localhost:8091/realms/my-realm
  kafka:
    bootstrap-servers: localhost:9092
    bookingTopic: bookingRequest
